modLoader="javafml" #mandatory
loaderVersion="[41,)"
issueTrackerURL="https://github.com/TeamTwilight/twilightforest/issues" #optional
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="twilightforest"
version="${file.jarVersion}"
displayName="The Twilight Forest"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest" #optional
updateJSONURL="https://raw.githubusercontent.com/TeamTwilight/twilightforest/1.19.x/update.json"
logoFile="twilightforest_logo.png" #optional
credits="By Benimatic (Ben Mazur)" #optional
authors="Benimatic, AtomicBlom, Drullkus, Killer_Demon, quadraxis, Tamaized, williewillus, Andromander, GizmoTheMoonPig, Jodlodi" #optional
description='''
An enchanted forest dimension.
'''

[[dependencies.twilightforest]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.21,)"
    ordering="NONE"
    side="BOTH"
