modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/TeamTwilight/twilightforest/issues"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="twilightforest"
version="${file.jarVersion}"
displayName="The Twilight Forest"
itemIcon="twilightforest:twilight_portal_miniature_structure"
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest"
updateJSONURL="https://gh.tamaized.com/TeamTwilight/twilightforest/update.json"
logoFile="twilightforest_logo.png"
credits="By Benimatic (Ben Mazur)"
authors="Benimatic, AtomicBlom, Drullkus, Killer_Demon, quadraxis, Tamaized, williewillus, Andromander, GizmoTheMoonPig, jodlodi"
description='''
An enchanted forest dimension.
'''

[[dependencies.twilightforest]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.twilightforest]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[modproperties.twilightforest]
    configuredBackground="twilightforest:textures/block/mazestone_large_brick.png"